- hosts: localhost
  tasks:
    - name: install pre-req
      become: true
      become_user: root
      apt:
        state: present
        name:
         - make
         - cmake
         - libtool
         - libtool-bin
         - gettext
         - autoconf
         - automake
         - g++
         - pkg-config
         - unzip
         - curl
         - doxygen

    - name: clone neovim
      ansible.builtin.git:
        repo: git@github.com:neovim/neovim.git
        dest: /tmp/neovim
        version: release-0.5

    - name: build nvim
      become: true 
      community.general.make:
        chdir: /tmp/neovim
        jobs: 4
        params:
          CMAKE_BUILD_TYPE: Release

    - name: install nvim
      become: true 
      community.general.make:
        chdir: /tmp/neovim
        target: install
        params:

    - name: create config path
      file:
        path: ~/.config/nvim
        state: directory

    - name: remove vimrc 
      ansible.builtin.file:
        state: absent
        path: ~/.config/nvim/init.vim

    - name: symbolic link vimrc 
      file:
        src: "{{ playbook_dir }}/nvimrc" 
        dest: ~/.config/nvim/init.vim
        state: link
        backup: yes

    - name: setup vimplug
      shell: curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      register: result

    - name: install plugins
      shell: nvim +PlugInstall +qall
      register: result
