- hosts: localhost
  tasks:
    - name: install zsh 
      become: true
      become_user: root
      apt:
        state: present
        name:
         - zsh

    - name: symbolic link .zshrc
      file:
        src: "{{ playbook_dir }}/.zshrc"
        dest: "~/.zshrc"
        state: link

    - name: set zsh as default 
      become: true
      become_user: root
      shell: chsh -s /bin/zsh liam
      register: result


